处理缺失数据

In [1]:
import pandas as pd
import numpy as np

In [2]:
float_data = pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [4]:
float_data = pd.Series([1,2,None],dtype="float64")
display(float_data)

0    1.0
1    2.0
2    NaN
dtype: float64

过滤缺失数据

In [5]:
data = pd.Series([1,np.nan,3.5,np.nan,7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [6]:
data.dropna()
# data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [9]:
display(data)
data.dropna(how="all")
# 只删除行为NA

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data[4] = np.nan

In [11]:
data.dropna(axis=1,how="all")
# how to drop

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
display(df)

          0         1         2
0  1.243484  0.507744  0.835163
1 -0.076418  0.111700 -1.013368
2  0.262427 -0.016603  1.862489
3 -0.545994 -1.048251  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

In [13]:
df.iloc[:4,1] = np.nan
df.iloc[:2,2] = np.nan
df
# 取值时：一般是先行后列
# 创建/理解表结构时：常常先列后行

          0         1         2
0  1.243484       NaN       NaN
1 -0.076418       NaN       NaN
2  0.262427       NaN  1.862489
3 -0.545994       NaN  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

In [14]:
df.dropna(thresh=2)
# 指定保留缺失观测值的行

          0         1         2
2  0.262427       NaN  1.862489
3 -0.545994       NaN  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

填充缺失数据

In [15]:
df

          0         1         2
0  1.243484       NaN       NaN
1 -0.076418       NaN       NaN
2  0.262427       NaN  1.862489
3 -0.545994       NaN  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

In [16]:
df.fillna(0)

          0         1         2
0  1.243484  0.000000  0.000000
1 -0.076418  0.000000  0.000000
2  0.262427  0.000000  1.862489
3 -0.545994  0.000000  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

In [17]:
df.fillna({1:0.5,2:1})
# 通过传入一个字典将缺失值修改为不同填充值

          0         1         2
0  1.243484  0.500000  1.000000
1 -0.076418  0.500000  1.000000
2  0.262427  0.500000  1.862489
3 -0.545994  0.500000  0.482823
4  1.013460  0.023364 -2.136266
5 -0.685733 -0.862155  1.204126
6 -0.858191 -1.300200  0.210353

In [18]:
df = pd.DataFrame(np.random.standard_normal((6,3)))

In [19]:
df.iloc[2:,1] = np.nan
df.iloc[4:,2] = np.nan
df

          0         1         2
0 -0.267089  0.185257  2.114857
1 -0.425269 -0.633389  0.596138
2  1.767110       NaN  0.053897
3  1.213269       NaN -1.054087
4  0.038347       NaN       NaN
5 -1.128389       NaN       NaN

In [20]:
df.ffill()
# 向前填充 forward fill
# 向后填充bfill

          0         1         2
0 -0.267089  0.185257  2.114857
1 -0.425269 -0.633389  0.596138
2  1.767110 -0.633389  0.053897
3  1.213269 -0.633389 -1.054087
4  0.038347 -0.633389 -1.054087
5 -1.128389 -0.633389 -1.054087

In [21]:
df.ffill(limit=2)

          0         1         2
0 -0.267089  0.185257  2.114857
1 -0.425269 -0.633389  0.596138
2  1.767110 -0.633389  0.053897
3  1.213269 -0.633389 -1.054087
4  0.038347       NaN -1.054087
5 -1.128389       NaN -1.054087

In [22]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [23]:
data.fillna(data.mean())
# 按照中位数等填充

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

删除重复值

In [24]:
data = pd.DataFrame({"K1":["one","two"]*3 + ["two"],
                     "K2":[1,1,2,3,3,4,4]})
data

    K1  K2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [25]:
data.duplicated()
# 判断每一行是不是重复行。
# 它返回一个布尔型 Series：
# True：这一行和前面某一行重复
# False：这一行第一次出现，不算重复

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [26]:
data.drop_duplicates()

    K1  K2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [27]:
data["v1"] = range(7)

In [28]:
data

    K1  K2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [29]:
data.drop_duplicates(subset=["K1"])

    K1  K2  v1
0  one   1   0
1  two   1   1

使用函数或映射转换数据

In [30]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                                                             "pastrami", "corned beef", "bacon",
                               "pastrami", "honey ham", "nova lox"],
                        "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [31]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [32]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [33]:
data['animal'] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

替换值

In [34]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [35]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [36]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [37]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

重命名轴索引

In [38]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                                         index=["Ohio", "Colorado", "New York"],
                     columns=["one", "two", "three", "four"])

In [39]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [40]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)
# 把 data 的索引逐个拿出来处理，取前 4 个字符并转成大写

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

离散化与分箱

In [41]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [42]:
bins = [18,25,35,60,100]

In [43]:
age_categories = pd.cut(ages,bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [44]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [45]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [46]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [47]:
pd.cut(ages,bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [48]:
data = np.random.uniform(size=20)
data

array([0.94067318, 0.55308308, 0.34839277, 0.02840468, 0.54752904,
       0.63386554, 0.45154069, 0.82600727, 0.75791259, 0.9771017 ,
       0.2128799 , 0.81552541, 0.82227366, 0.65202329, 0.30309451,
       0.53279238, 0.13775904, 0.24516662, 0.13542963, 0.08789514])

In [49]:
pd.cut(data, 4, precision=2)
# 四等分，小数点精确到两位

[(0.74, 0.98], (0.5, 0.74], (0.27, 0.5], (0.027, 0.27], (0.5, 0.74], ..., (0.5, 0.74], (0.027, 0.27], (0.027, 0.27], (0.027, 0.27], (0.027, 0.27]]
Length: 20
Categories (4, interval[float64, right]): [(0.027, 0.27] < (0.27, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [50]:
data =np.random.standard_normal(1000)
data

array([-1.02983384e+00,  6.75487549e-01, -9.38440178e-01,  2.59953068e+00,
       -2.88332726e-01,  1.16053220e-01,  1.44286633e+00,  3.57593389e-02,
        1.11168439e+00,  1.55782990e-01, -3.70514610e-01, -8.02345227e-01,
       -1.51283440e-01, -1.05721770e-03,  3.00949590e+00, -1.89091356e+00,
        9.22696004e-01,  7.11897260e-01, -1.70547824e-01, -2.03030429e+00,
       -3.17349433e-01,  3.12677593e-01, -8.06516135e-01,  5.48950753e-02,
        3.79473765e-01, -1.46897670e+00,  1.02010480e-01,  6.08682866e-01,
        1.10576224e+00,  6.53367242e-01, -1.13743321e+00,  1.20349795e-01,
        2.35438948e+00,  8.43101965e-01, -2.05402114e+00, -9.16748358e-01,
       -1.01272484e+00,  1.87869473e+00, -7.43592757e-01, -9.94067861e-03,
        1.23723254e+00, -6.90490428e-01,  1.59042868e+00, -6.96346434e-01,
        1.41468468e+00, -1.49898941e+00, -1.58792676e-01, -1.26106070e+00,
       -1.11569498e+00, -1.39646215e-01,  7.40242796e-01, -6.50882512e-02,
       -6.13381225e-01,  2.34130823e+00, -1.32654518e+00,  2.69809735e-01,
        1.07502580e+00,  7.00682881e-01, -1.56596303e-01, -1.19267638e+00,
        2.22172930e-01,  1.23179870e+00,  4.18774732e-01, -6.14625362e-01,
        5.53880588e-01,  2.04782237e-01,  3.81166753e-01,  5.75538175e-01,
        2.24544594e-01, -1.85964348e+00, -8.19002139e-01, -5.59418045e-01,
       -2.37024639e+00,  1.10123905e+00, -1.39448068e-01,  1.69252631e+00,
       -1.36473196e+00, -5.90991708e-02,  1.04727929e+00,  7.91950187e-01,
       -1.52533512e+00,  1.06952548e+00,  1.62837325e+00, -7.55975456e-01,
       -6.90982387e-02, -2.80163853e-01, -1.77181085e+00,  1.38518411e+00,
        1.16214251e+00, -2.14070235e-01,  2.16147452e-01,  6.81050846e-01,
       -4.89474254e-01,  8.41923492e-01,  4.78123473e-01,  9.56067237e-01,
       -8.44866216e-01, -1.54643155e+00, -5.66141373e-01,  4.71923415e-01,
        1.36170954e+00,  2.56373685e-01, -4.05214591e-01,  7.36956858e-01,
       -2.34178372e+00, -5.16023628e-01, -1.10143673e+00,  4.71859229e-01,
        8.44518559e-01,  3.17623093e-01, -1.96801868e+00,  2.26616107e-01,
        1.40477138e+00, -2.21790092e-01,  9.03789471e-01, -4.89776805e-01,
       -4.54602472e-02,  1.69515267e-01, -1.88149445e+00, -7.22542768e-01,
       -8.74801573e-02,  1.91822252e+00,  6.58354347e-01,  1.80783699e-01,
        3.84264476e-01,  1.14258951e+00, -2.49208956e-02,  2.51938314e-01,
       -1.30237449e-01, -1.58662266e+00, -7.88829498e-01,  7.08274873e-01,
        3.09744960e-01,  3.86714761e-01,  7.56205498e-01,  7.38061072e-01,
       -2.95234878e-02, -3.09960274e-01, -1.58347556e-01, -8.79462700e-02,
       -5.85528148e-01,  6.39622128e-01, -8.11529578e-01, -7.97238909e-01,
       -6.05337085e-02,  1.57396654e-01, -3.72954359e-01, -7.91588699e-01,
        4.57296347e-01, -4.95474331e-02, -3.98254754e-01, -1.18544812e+00,
        1.85969228e-02, -2.69734343e-01, -1.68786182e-01,  4.54761813e-02,
       -7.51551751e-02, -6.48049365e-01, -2.69484570e-01,  1.69860640e+00,
        1.88861139e+00, -5.44859218e-01, -1.42235714e+00, -1.70669107e+00,
       -4.06217275e-01, -1.44917715e+00,  7.54989803e-01,  4.58087299e-02,
        2.27678244e+00,  1.85594314e+00,  1.55102475e+00, -1.37634015e+00,
        1.20137836e+00, -3.41600811e-01,  5.95872544e-01, -9.97153895e-01,
       -2.35087497e+00, -1.16901757e+00, -1.10156606e+00,  1.64764973e+00,
        3.71657261e-01, -4.75182514e-01, -5.91119324e-01, -1.37585124e+00,
        2.57110057e+00, -4.45093261e-01,  1.79739702e+00, -3.75758569e-01,
        5.13815995e-01, -6.87352883e-01,  1.68027596e+00, -1.09672818e-01,
       -1.23982257e-01,  6.91345690e-01, -4.85452661e-01,  7.50393731e-01,
        8.76821340e-01,  1.08179381e+00, -4.54303657e-01, -3.06950908e-01,
       -9.07027573e-03, -4.04833990e-01,  7.96453264e-01, -5.48012176e-01,
       -4.46019901e-01, -6.76873054e-03,  6.46970325e-01,  6.70423931e-01,
       -7.68550718e-01,  1.37515116e-01,  6.74916627e-01, -4.38077167e-01,
       -3.90505171e-02, -3.34140505e-01,  2.54062776e+00, -5.49394993e-03,
        6.93578912e-01,  3.66665238e-01, -9.02465545e-01, -2.83497983e-01,
        5.08866113e-01,  3.08005779e-01, -7.48684008e-01, -7.58692752e-01,
        1.49984514e+00, -2.25915914e+00,  5.45597601e-01, -1.23794850e+00,
        1.94530310e-01,  1.83807283e+00,  1.13745083e+00,  1.29143600e+00,
       -1.30807734e+00, -1.20617509e+00,  8.10293095e-01, -1.02026533e+00,
       -8.85455429e-03,  1.22081889e+00, -5.44736596e-01, -4.56287745e-01,
       -1.68623494e+00, -3.11455960e-01,  2.09213524e+00, -6.29196991e-01,
       -9.16416172e-02,  1.13201105e-01,  1.10457263e+00, -2.18887102e-01,
       -3.85259967e-01,  9.92910599e-01, -5.23684154e-01,  1.07994274e+00,
       -8.63211233e-01,  8.04532653e-01, -4.84474986e-02, -1.06024887e+00,
       -8.35375507e-01, -5.14055363e-01, -1.61357359e+00,  3.81963097e-01,
        3.08216803e-01, -6.69512473e-01, -2.19451856e+00,  1.97200844e-01,
       -5.62184376e-01,  1.12942462e+00,  4.56586275e-01, -7.16147083e-01,
       -6.55341473e-01,  2.32800410e-01,  7.55725668e-01,  1.22203304e+00,
        2.57294171e-01, -5.62903576e-01, -5.49895734e-01, -8.52179626e-01,
        1.86165919e+00,  1.44727748e+00,  1.11103745e+00, -1.05018671e+00,
       -5.13578307e-01, -2.05166629e+00, -8.56113261e-01,  7.92576681e-01,
       -1.12529250e+00,  4.44485166e-01, -1.48399836e+00,  1.30275995e+00,
       -6.68512549e-01,  4.69450172e-01,  3.01687079e-01,  7.33409752e-01,
        2.78915115e-01, -9.29038559e-01, -5.63531597e-01, -6.38774595e-01,
       -1.69036612e-02,  2.69340059e-01, -1.87413585e-01,  1.22126783e+00,
       -1.09647385e+00, -2.65421091e+00, -1.10711587e+00,  1.54853208e+00,
       -2.22278166e-01,  6.61530062e-01,  1.39792443e+00, -9.78674325e-01,
        3.65073144e-01, -2.69128663e-01, -3.69752683e-01,  2.56871345e-01,
       -4.57544873e-01,  8.81617188e-01, -3.77084626e-01, -5.28069032e-01,
        7.77241301e-01, -1.12320723e+00, -9.83174116e-01,  3.05553750e-01,
       -8.13562581e-01, -1.25243257e-01,  1.13652060e+00, -2.80507545e-01,
        4.67309736e-02,  1.39668842e-01, -5.03721211e-01,  4.99934609e-01,
        1.49932404e+00, -2.38237187e-01,  1.23997707e+00, -6.96446571e-02,
       -6.80438132e-01, -3.58618157e-01, -4.38891674e-01, -1.23618382e+00,
       -3.13113765e-01, -1.26565856e+00,  1.13232882e-01, -5.14871303e-01,
       -1.09041167e+00,  7.14854716e-01, -1.91455106e+00, -3.55960890e-01,
        6.10602331e-01,  1.08525422e+00, -2.53580717e-01, -1.24241555e+00,
       -1.08615589e+00, -7.59557736e-01,  1.00379752e+00, -9.49352450e-01,
       -1.31531008e+00,  1.93924898e+00,  1.13153048e+00,  8.72068766e-01,
       -5.59088494e-01, -2.67659414e-01,  9.65702094e-01, -3.49370799e-01,
        1.41404600e-02, -1.88165194e+00,  7.52024969e-01,  1.70265334e+00,
        1.79967009e-01,  8.84029620e-01,  1.03250163e+00, -5.28234976e-01,
        1.69460176e+00, -7.61166996e-01, -6.43215252e-02,  7.74930331e-01,
       -4.87061196e-01, -9.43066556e-01, -1.63501972e-01,  5.41738018e-01,
       -8.62551931e-01,  1.29745443e+00, -3.67350832e-01, -2.16313166e-01,
        5.44550415e-01,  9.35182845e-01,  8.04384267e-01,  2.02057709e+00,
        9.52632778e-01, -8.42067036e-01, -1.78081583e+00,  1.46461633e-01,
       -8.83360781e-01,  5.80034570e-01, -1.02820707e+00, -6.26006452e-01,
       -1.09512846e+00,  2.00391950e-01,  4.80126680e-01, -6.16352925e-01,
        8.74220485e-01, -1.83708088e+00, -2.43868920e-01,  1.60492327e-01,
       -1.13084701e-01,  1.16764881e-01, -7.93663073e-01, -1.14559900e+00,
       -1.72417781e+00, -1.82105462e-01,  1.62480504e+00, -5.67686835e-02,
        3.36792103e-02, -1.51279353e+00,  4.88051783e-02,  8.13692928e-01,
       -1.57163536e-01, -1.93803321e-01,  6.40754303e-01,  1.75260374e-01,
       -5.56186662e-01,  3.23205706e-01,  1.41239569e+00,  1.44275994e+00,
       -1.76466017e+00, -1.18647739e-01, -1.37053057e+00,  9.79961270e-01,
        3.44190138e-01, -7.99839249e-01, -3.62344654e-02, -5.46590302e-02,
       -1.70012920e+00,  6.11468838e-01,  5.97687492e-01, -1.25083064e+00,
        1.19202989e+00,  8.59590697e-01,  1.21752697e+00,  1.54435099e-01,
        3.81839541e-01, -8.97030902e-01,  8.19763127e-01,  1.56656821e+00,
        7.77397891e-02,  1.16335555e+00, -1.19024932e-01, -1.86996617e+00,
        2.86259582e-01, -1.96309304e+00, -5.67736792e-01,  1.63849669e+00,
        9.32214284e-01, -1.22392456e+00, -5.93785211e-01,  6.59269333e-01,
        8.76241603e-01,  6.84730277e-01, -3.81944550e-01, -9.94674005e-02,
        3.46036956e-01, -8.91239647e-01,  1.05764063e+00, -6.44725623e-01,
       -1.32316738e+00, -7.51580120e-01,  6.39181924e-01,  4.11386270e-02,
        8.75818204e-01, -1.39255764e-01, -6.65237771e-01,  8.72081327e-03,
       -1.66663065e+00, -4.59535448e-01, -1.73223969e-01, -1.58024231e-01,
        1.16245252e+00, -5.32451383e-01, -1.63445065e+00,  3.79573728e-01,
        1.00620871e-01,  7.70537720e-01,  4.80231166e-01,  5.67857201e-01,
        4.22536231e-01,  1.10481823e-02, -1.51506296e+00, -9.74472081e-01,
        1.39488687e+00, -7.13638145e-01,  1.07902796e+00,  2.03970019e-01,
       -8.11296257e-01,  1.23264371e+00,  3.12809458e-01, -4.76856895e-01,
        3.48843814e-03, -4.43088192e-01,  1.26595761e-01, -1.51071261e+00,
       -7.31027450e-02, -8.14479941e-01, -6.18495287e-02, -5.15749190e-01,
       -2.50019711e-01, -7.05407558e-01,  2.69812457e-01, -2.25846708e+00,
       -1.67681994e+00,  1.14445379e+00,  4.08266861e-01, -4.70425917e-01,
        2.86599215e-01,  9.74721875e-01,  1.78384210e-01,  1.26902561e+00,
        2.54460790e+00,  7.68521909e-01, -2.55638549e-01, -7.74551624e-01,
       -1.09560941e+00,  2.81314642e-01, -5.04363114e-01,  3.93276514e-02,
       -1.78584403e+00,  7.42915008e-01, -6.58451901e-01,  1.11111496e+00,
        4.16834106e-01,  6.88980350e-01, -3.95741766e-01, -9.84101490e-01,
       -4.76581936e-01, -2.33131468e-01, -6.76057167e-01, -8.75411954e-01,
        1.03260139e+00, -8.16986537e-01,  8.18976256e-01,  5.53551165e-01,
       -6.13344994e-01,  1.80060523e-01,  1.22378068e+00, -9.11539175e-02,
       -1.57016744e+00, -2.21908692e+00,  1.00842520e-01,  3.05904573e-01,
        1.38215899e+00,  1.72208784e+00, -6.58817468e-01, -6.04314149e-01,
       -1.34221322e+00, -1.20216437e+00, -1.19875246e+00, -7.32253527e-01,
       -6.20053577e-01, -9.38360219e-01,  9.65774845e-01,  2.02006246e-01,
       -1.53154280e+00, -6.16375477e-01, -2.05097890e+00,  3.41499630e-01,
       -1.01032582e+00,  3.81758031e-01, -7.06411210e-01,  6.53928679e-01,
       -1.84474996e+00, -1.46669878e+00, -4.89717714e-01, -1.20134858e+00,
       -3.61910290e-01,  9.85027925e-01, -3.74087905e-01,  1.20025146e+00,
        2.15053036e+00,  5.42885491e-01,  1.17743078e+00, -6.99976630e-01,
        1.15651823e+00, -1.46504789e+00,  6.40904326e-01,  8.00002372e-01,
       -6.11431171e-01, -1.72833135e+00,  7.42700962e-01, -7.39461401e-01,
        4.02208297e-01, -1.09289148e+00,  3.39684094e-01, -1.55400301e+00,
        1.04622784e+00, -1.17840593e+00, -1.50997732e+00,  8.90060421e-01,
        3.65103322e-01, -2.52680533e-01,  8.95818714e-01,  2.30162264e-01,
       -9.33129132e-01,  1.56064651e+00, -6.46554157e-01,  2.06570474e-02,
        2.56905629e+00, -8.50161365e-01,  2.43961403e-01,  6.52763405e-01,
       -1.44102122e+00, -8.66874244e-01,  1.08391089e-01,  9.51834541e-01,
        1.45311781e+00, -6.48763598e-01, -1.05913530e+00, -9.91064997e-01,
       -2.29359582e+00,  1.32490819e+00, -1.58662660e+00,  2.23618631e+00,
        1.00779486e+00, -1.11911452e+00,  2.54087666e+00,  6.57407237e-01,
       -4.18165500e-01,  1.29765244e+00, -1.45137531e+00,  2.36982569e-02,
       -2.71177687e-02, -4.36456236e-01,  1.32633301e+00, -1.11561936e+00,
        1.95845998e+00,  4.11154858e-01, -9.47277015e-01, -2.67097998e-01,
       -5.46405640e-01, -7.71451561e-01, -5.93866182e-01, -2.01497366e+00,
        1.57022548e+00,  9.76243362e-01,  1.46277237e+00,  1.17692516e-01,
        3.86642543e-01, -2.85885402e-01, -4.67106847e-02, -1.25528654e-01,
       -1.06386211e+00,  9.70101217e-01, -4.28747300e-01, -1.76063725e+00,
       -1.49437507e+00, -8.14251449e-01, -1.54055171e-01, -1.13800215e+00,
        2.20464556e+00,  4.62088532e-01, -5.64960747e-01,  3.62770123e-01,
       -2.46625353e-01,  2.81863675e-01, -4.47625802e-01,  6.51542196e-02,
        4.35263220e-01, -1.50822177e+00,  1.58131479e-01,  4.49167532e-01,
       -7.17565115e-01,  9.63219174e-02,  5.39515872e-01,  8.26560422e-01,
       -1.13419184e-01,  8.09791224e-01, -1.87815798e-01,  1.19634893e+00,
       -6.04531221e-01, -8.38408023e-01,  5.06929490e-01, -2.18816383e+00,
        8.19287782e-02,  5.01627291e-02, -3.77565801e-01, -1.09090205e+00,
       -1.10738041e+00,  1.36278081e-01, -1.02807718e-01, -4.67744200e-01,
        2.13281550e-01,  2.50199064e-01, -6.80938761e-01,  2.09604400e+00,
        5.40649545e-01,  1.56299734e-01, -8.76100094e-01,  1.38564516e-01,
        1.22007154e+00, -1.32179849e+00,  8.04200010e-01,  6.59877124e-02,
        2.12937107e+00, -4.68835420e-01,  3.56525881e-02, -1.04311074e+00,
        3.18179556e-01,  1.15609489e-01, -3.69339779e-01,  1.20365060e+00,
       -3.55359535e-01, -1.85001704e-01,  6.74246015e-01,  8.40055617e-01,
        8.09571840e-01, -1.34170986e+00,  1.14614393e+00, -3.87978318e-01,
       -8.92081913e-01, -2.07630144e+00,  7.99607691e-01, -1.89820055e+00,
       -4.91412363e-01, -1.34554571e+00,  1.02072858e+00,  8.37835105e-01,
        9.36752420e-01,  1.22250520e+00,  2.17688265e+00, -1.33755109e+00,
       -2.92148833e+00, -1.45201706e+00,  1.22915239e-01,  1.41206158e+00,
       -1.15481009e+00, -5.62446992e-02, -1.51949579e+00, -1.35864141e-01,
        6.02598751e-01, -3.85992720e-01,  2.14679638e+00, -8.54693594e-01,
       -1.02138114e-01,  9.20176189e-01,  7.89454579e-01, -2.55061827e-01,
        1.96706622e+00, -5.86202898e-01,  1.62378454e+00, -2.81084018e-01,
        1.52534166e-01,  1.42404993e+00, -5.43884944e-01, -2.05791572e+00,
       -7.12289669e-02, -6.98337938e-01, -1.42754714e+00, -1.75675596e+00,
        1.10932703e+00,  1.94259206e-01, -2.54750394e-01,  1.00983679e+00,
        1.49370822e-01,  1.17119875e+00,  9.09053674e-02,  5.17340551e-01,
        5.68459348e-01, -2.08234471e-01, -1.79199095e-01, -1.64747167e+00,
       -1.34477802e+00,  7.27497663e-01,  6.35726389e-01,  6.04067926e-01,
       -7.03973639e-01, -7.39162237e-01, -1.83250820e+00,  1.04520204e+00,
       -7.39044374e-01,  7.29936997e-01,  1.39623101e-01,  2.04685746e+00,
       -6.81545470e-01, -2.65626544e-01, -2.61579698e-01, -1.90725938e+00,
       -1.85476561e+00, -7.39655663e-01,  4.61998996e-01, -1.33325022e+00,
       -8.45684686e-01,  1.17173935e-01, -1.43427231e-02, -1.27177814e+00,
       -1.51459735e+00,  9.64046022e-01,  4.94622242e-01, -2.80508132e-02,
        7.55794340e-02, -2.71168843e-01,  2.18786740e+00, -2.12679033e+00,
        5.90604526e-01, -2.43986323e-01, -1.40708957e+00, -1.46188100e+00,
        7.43511076e-01,  7.32209656e-01,  1.68748339e-01,  9.51485598e-01,
        3.15968535e-01, -7.61360420e-01, -1.22611062e+00, -8.53206721e-01,
       -5.93702187e-01,  7.66382240e-01, -4.24786650e-01, -9.64652955e-01,
        1.99543953e-01,  9.51600788e-01,  6.04861735e-01, -1.62599647e+00,
       -5.15190532e-01, -2.93474139e-01, -2.05166371e+00, -1.20447239e+00,
        1.20931355e+00,  7.31501183e-01, -1.58401905e-01,  5.45529632e-01,
        3.73024053e-01,  8.17012425e-01, -6.49958093e-01,  7.49321918e-02,
       -3.48953887e-01,  1.52680505e+00, -1.04500880e+00, -2.16375670e+00,
       -1.17585007e+00, -7.29179539e-01, -3.80528097e-01,  1.60447082e-01,
        3.58311267e-01,  2.35450737e-01,  1.03032412e+00, -1.82439811e-01,
       -6.31239874e-01, -9.03990068e-01, -3.80202908e-01, -1.15746594e+00,
       -1.35721186e-01, -1.85169531e-01,  8.26380973e-01,  3.27068294e-01,
        1.74553535e-01,  1.44712730e-02, -8.71451584e-01, -1.77926602e+00,
        1.37920827e+00,  5.96986911e-01, -1.21194522e-01, -8.14734039e-01,
       -1.34938766e-01, -2.99397958e-01,  2.29648382e+00, -7.12742638e-01,
       -5.38549462e-02, -1.10906856e+00,  6.91663166e-01, -8.99293840e-01,
       -1.29327161e+00, -1.27200007e+00, -5.84783413e-01, -7.55641002e-01,
       -7.01118175e-01,  2.40531125e-01, -8.14792862e-01, -1.12237403e+00,
        2.71631292e-01, -4.34846345e-01,  5.51322830e-01, -1.28736924e+00,
       -1.99022459e+00, -9.80773485e-01,  6.92032140e-01, -1.47604488e+00,
       -1.21225215e+00, -1.35194506e-01,  9.12943825e-04, -6.44837813e-01,
        6.90051514e-01,  1.13040434e-01,  1.13218683e+00, -1.10650791e+00,
        8.99529967e-02,  5.08077035e-01, -1.21018386e+00,  2.39830744e-01,
       -8.51421050e-01, -1.27698587e+00,  4.54971581e-01, -1.76983255e+00,
        4.96049573e-01, -1.35214379e+00,  2.06533103e+00,  2.91813065e-01,
       -2.76709693e-01, -2.41820848e-01,  2.25258712e-01, -2.74300702e+00,
       -3.76879169e-01, -1.81635227e-02, -1.11423383e-01, -1.33372760e+00,
       -9.70112064e-01, -7.90474924e-01,  3.44119572e-01, -1.25579835e+00,
       -7.70090640e-01, -1.44668836e+00,  9.03663747e-01, -1.84464586e-01,
        1.04155040e+00,  1.59328822e+00,  8.27718305e-01,  5.52234995e-01,
        1.67962713e-01,  1.67172978e+00, -1.96084802e-01, -3.09561648e-01,
       -8.11665834e-01,  5.55337239e-01, -3.35615806e-01, -6.93437579e-01,
       -6.40246109e-01,  1.05087864e+00,  2.92394759e-01,  2.40329412e+00,
       -9.21041721e-03, -6.15490948e-01, -6.05126487e-01, -1.44235764e+00,
        4.89280994e-01,  2.62493828e-01, -6.21839200e-02,  3.75545661e-02,
        7.39852196e-01,  1.40425031e+00, -1.42885570e+00,  8.18986719e-01,
        8.99633844e-01,  7.37803680e-01, -3.04295796e-01,  1.52472768e+00,
       -8.36646155e-01,  3.85956865e-01, -1.31131174e+00, -7.83130620e-01,
       -1.22900212e+00,  3.91941148e-01,  3.11698298e-01, -1.77557102e-01,
       -1.45240353e-01,  5.97411190e-01, -4.79842947e-01,  3.19894832e-02,
       -7.21226043e-01,  5.04743158e-01, -1.33131146e+00, -9.73415623e-01,
        6.64835868e-01, -7.24906382e-01, -4.64946687e-01,  2.75507606e-01,
        6.51945248e-01, -3.19709053e-01,  7.43599686e-01,  7.16177469e-01,
        1.06264395e+00,  1.55037436e+00, -1.97952361e-02, -6.43784478e-01,
        7.38682063e-01,  1.37157452e+00, -7.94563515e-01,  1.08022587e+00,
       -4.47581120e-01,  4.03375124e-01, -2.29131179e-01, -3.93115583e-02,
       -1.17043125e+00, -4.63772221e-01, -6.39067221e-01, -8.23068789e-01,
        4.88338626e-01, -5.44969321e-01,  1.68970456e-01,  5.57288136e-01,
        6.07016782e-01, -1.20155529e-01, -1.09723812e-01,  5.07582188e-01,
       -1.05820466e+00,  5.94389140e-01,  9.93580488e-01, -5.41755744e-01])

In [51]:
quantiles = pd.qcut(data,4,precision=4)
quantiles

[(-2.9216, -0.7392], (0.6521, 3.0095], (-2.9216, -0.7392], (0.6521, 3.0095], (-0.7392, -0.07044], ..., (-0.07044, 0.6521], (-2.9216, -0.7392], (-0.07044, 0.6521], (0.6521, 3.0095], (-0.7392, -0.07044]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9216, -0.7392] < (-0.7392, -0.07044] < (-0.07044, 0.6521] < (0.6521, 3.0095]]

In [52]:
quantiles.value_counts()
# cut：按数值区间等宽分箱
# qcut：按分位数分箱，尽量每箱数量差不多

(-2.9216, -0.7392]     250
(-0.7392, -0.07044]    250
(-0.07044, 0.6521]     250
(0.6521, 3.0095]       250
Name: count, dtype: int64

In [53]:
pd.qcut(data,[0,0.1,0.5,0.9,1.]).value_counts
# 自定义分位数（必须介于0和1）

<bound method Categorical.value_counts of [(-1.332, -0.0704], (-0.0704, 1.179], (-1.332, -0.0704], (1.179, 3.009], (-1.332, -0.0704], ..., (-0.0704, 1.179], (-1.332, -0.0704], (-0.0704, 1.179], (-0.0704, 1.179], (-1.332, -0.0704]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.9219999999999997, -1.332] < (-1.332, -0.0704] < (-0.0704, 1.179] < (1.179, 3.009]]>

检测和过滤异常值

In [54]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))
display(data)

            0         1         2         3
0   -0.125264  0.281723 -1.421569 -0.958345
1   -0.777573 -1.160927 -0.133992  0.626035
2   -0.125115  0.188659 -1.137374  1.050663
3    0.937283 -1.346712  2.020071 -0.050500
4    1.358082 -0.213689  1.148799 -0.729244
..        ...       ...       ...       ...
995  0.592833 -0.530172 -0.293296 -0.466130
996  0.838622  0.119662  0.511838  0.223750
997  0.618795  1.731123 -0.273986 -0.495603
998  0.632332  2.593766  0.526098  1.872899
999 -0.446801  0.444665 -1.172054 -1.157363

[1000 rows x 4 columns]

In [55]:
col = data[2]
col[col.abs() > 3]
# 找出指定列绝对值大于三的值

311    3.199901
Name: 2, dtype: float64

In [56]:
data[(data.abs()>3).any(axis=1)] #按行处理
# 把 data 中“任意一列的值超过 3（不管正负）”的那些行筛选出来

            0         1         2         3
175  0.569328 -0.794009 -0.026840  3.727234
185  1.088257 -3.211266 -0.165890  0.258000
199 -0.169044  3.511545  1.786111 -0.549762
311 -0.749342  0.367329  3.199901  0.345169
319  1.703117  1.107585 -0.376354  3.096749
364  1.229804  1.759018  0.951776  3.085080
473 -0.732478 -3.216200 -0.805012  0.150275
548  1.451748 -0.057335 -0.212131  3.180173
852 -0.077300 -0.229977  0.320501  3.344195

In [57]:
data[data.abs() > 3] = np.sign(data) * 3
# 把 data 中绝对值大于 3 的元素截断到 3 或 -3
# np.sign() 会返回每个数的符号：
# 正数 -> 1
# 负数 -> -1
# 0 -> 0
display(data)

            0         1         2         3
0   -0.125264  0.281723 -1.421569 -0.958345
1   -0.777573 -1.160927 -0.133992  0.626035
2   -0.125115  0.188659 -1.137374  1.050663
3    0.937283 -1.346712  2.020071 -0.050500
4    1.358082 -0.213689  1.148799 -0.729244
..        ...       ...       ...       ...
995  0.592833 -0.530172 -0.293296 -0.466130
996  0.838622  0.119662  0.511838  0.223750
997  0.618795  1.731123 -0.273986 -0.495603
998  0.632332  2.593766  0.526098  1.872899
999 -0.446801  0.444665 -1.172054 -1.157363

[1000 rows x 4 columns]

In [58]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.013591     0.006903    -0.039916     0.021178
std       0.935270     0.976650     0.973705     0.998315
min      -2.992156    -3.000000    -2.839603    -2.938692
25%      -0.620593    -0.659609    -0.695331    -0.665081
50%      -0.018796     0.006074    -0.031498     0.025969
75%       0.712927     0.675249     0.578067     0.689937
max       2.805436     3.000000     3.000000     3.000000

In [59]:
np.sign(data).head(10)

     0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0 -1.0  1.0 -1.0
4  1.0 -1.0  1.0 -1.0
5 -1.0 -1.0 -1.0  1.0
6 -1.0  1.0  1.0  1.0
7 -1.0 -1.0  1.0 -1.0
8  1.0 -1.0  1.0 -1.0
9  1.0 -1.0  1.0  1.0

排列和随机抽样

In [60]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5,7)))
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [61]:
sampler = np.random.permutation(5)
display(sampler)
# 将0 到 4 这 5 个整数随机打乱顺序

array([4, 1, 3, 0, 2])

In [62]:
df.take(sampler)
# take() 是按位置索引取值，不是按标签取值

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [63]:
df.iloc[sampler]

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [64]:
column_sampler = np.random.permutation(7)
column_sampler

array([6, 5, 4, 1, 2, 0, 3])

In [65]:
df.take(column_sampler,axis=1)

    6   5   4   1   2   0   3
0   6   5   4   1   2   0   3
1  13  12  11   8   9   7  10
2  20  19  18  15  16  14  17
3  27  26  25  22  23  21  24
4  34  33  32  29  30  28  31

In [66]:
df.sample(3)
# 从 df 中随机抽取 3 行

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [67]:
choice = pd.Series([5,7,-1,6,4])
choice.sample(n=10,replace=True)
# 从 choice 这 5 个数里随机抽 10 次，并且允许重复抽到同一个值

2   -1
4    4
1    7
0    5
2   -1
3    6
1    7
2   -1
4    4
0    5
dtype: int64

计算指示/虚拟变量

In [68]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": range(6)})

In [69]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [70]:
pd.get_dummies(df["key"],dtype=float)
# 把 df["key"] 这一列的分类值转换成哑变量矩阵
# 把文字类别变成计算机更容易处理的数字形式

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [71]:
dummies = pd.get_dummies(df["key"],prefix="key",dtype=float)
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy
# 先把 key 列做成哑变量，再把这些哑变量列拼接到 data1 那一列旁边
# 通过prefix="key",列名变成key_a key_b key_c
# df[['data1]]取出原表的data1，使用双中括号，结果还是DataFrame而不是Series
# 通过join()横向拼接

   data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [72]:
mnames = ['movie_id','title','genres']
movies = pd.read_table("datasets/movielens/movies.dat",sep="::",header=None,names=mnames,engine="python")
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [73]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10,:6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [74]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]
#将dummies的列名加到Genre后，然后拼接到movies表，在查看第一行数据

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [75]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [76]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))
# pd.get_dummies 讲区间标签转成哑变量

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

扩展数据类型

In [77]:
s = pd.Series([1,2,3,None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [78]:
s.dtype
# NaN 属于浮点体系
# type(s)看对象类型，s.dtype看数据类型

dtype('float64')

In [79]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [80]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [81]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [82]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [83]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [84]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                    "B": ["one", "two", "three", None],
                    "C": [False, None, False, True]})

In [85]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0    NaN   True

In [86]:
type(df)

pandas.DataFrame

In [87]:
df.dtypes

A    float64
B        str
C     object
dtype: object

字符串操作

In [88]:
val = 'a,b,  guido'
val.split(",")

['a', 'b', '  guido']

In [89]:
pieces = [x.strip() for x in val.split(',')]
pieces
# split与strip结合删除空白字符

['a', 'b', 'guido']

In [ ]:
first, second,  third = pieces
# 序列解包
first + "::"  + second + "::" + third

'a::b::guido'

In [ ]:
"::".join(pieces)
# 等价于

'a::b::guido'

In [ ]:
"guido" in pieces
# 使用in关键词检测子字符串

True

In [ ]:
display(val)
val.replace(",","::")
# 将,替换为：：

'a,b,  guido'

'a::b::  guido'

正则表达式

In [94]:
import re

In [96]:
text = "foo.   bar\t.   baz.   \tqux"
text

'foo.   bar\t.   baz.   \tqux'

In [97]:
re.split(r"\s+",text)

['foo.', 'bar', '.', 'baz.', 'qux']

In [99]:
regex = re.compile(r"\s+")
regex.split(text)
# 先编译一个“匹配一个或多个空白字符”的正则表达式，再用它去切分字符串 text

['foo.', 'bar', '.', 'baz.', 'qux']

In [100]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [ ]:
regex = re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)
# flags= 匹配是额外采用的规则

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [102]:
m = regex.search(text)
m

In [104]:
print(regex.sub("REDACTED",text))
# 将匹配值替换为指定值

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [106]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern,flags = re.IGNORECASE)

In [108]:
m = regex.match("wesm@bright.net")
m

In [ ]:
m.groups()
# match()从字符串开头开始匹配，group()则从匹配结果中取出匹配内容

('wesm', 'bright', 'net')

In [110]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))
# 通过\1,\2访问匹配的分组

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

In [124]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
         "Rob": "rob@gmail.com", "Wes": np.nan}

In [125]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: str

In [126]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [127]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [128]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [129]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [130]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: str

分类数据

In [132]:
values = pd.Series(['apple', 'orange', 'apple',
                     'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: str

In [133]:
pd.unique(values)

<StringArray>
['apple', 'orange']
Length: 2, dtype: str

In [137]:
values.value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [138]:
dim = pd.Series(['apple','orange'])
dim

0     apple
1    orange
dtype: str

In [141]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

In [142]:
df = pd.DataFrame({'fruit': fruits,
                    'basket_id': np.arange(N),
                     'count': rng.integers(3, 15, size=N),
                    'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [143]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
fruit_cat = df['fruit'].astype("category")
# 把 df['fruit'] 这一列从普通字符串列，转换成“分类类型”列
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [146]:
c = fruit_cat.array
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, str): ['apple', 'orange']

In [147]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [148]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
df['fruit'] = df['fruit'].astype('category')
# 通过赋值的方法将DataFrame列转化为分类数据

In [150]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, str): ['apple', 'orange']

In [151]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
# 直接创建

In [152]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, str): ['bar', 'baz', 'foo']

In [ ]:
categories = ['foo', 'bar', 'baz']
codes = [0,1,2,0,0,1]
my_cats_2 = pd.Categorical.from_codes(codes,categories)
my_cats_2
# 根据编码直接构造

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, str): ['foo', 'bar', 'baz']

对分类数据的计算

In [154]:
rng = np.random.default_rng(seed=12345)
# random number generator
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [155]:
bins = pd.qcut(draws,4)

In [156]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [157]:
bins = pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [159]:
bins.codes[:10]
# 前十个值落在哪号箱

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
bins =pd.Series(bins,name='quartitle')
results = (pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())
# 按分箱区间对 draws 分组，统计每个区间的数量、最小值和最大值
results

  quartitle  count       min       max
0        Q1    250 -3.119609 -0.678494
1        Q2    250 -0.673305  0.008009
2        Q3    250  0.018753  0.686183
3        Q4    250  0.688282  3.211418

In [162]:
results['quartitle']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartitle, dtype: category
Categories (4, str): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [164]:
categories = pd.Series(['foo','bar','baz','qux']*2).astype('category')
categories

0    foo
1    bar
2    baz
3    qux
4    foo
5    bar
6    baz
7    qux
dtype: category
Categories (4, str): ['bar', 'baz', 'foo', 'qux']

In [ ]:
categories.memory_usage(deep=True)

380

In [166]:
pd.Series(['foo','bar','baz','qux']*2).memory_usage(deep=True)

612

In [167]:
%time _ = categories = pd.Series(['foo','bar','baz','qux']*2).astype('category')
categories

CPU times: user 682 μs, sys: 73 μs, total: 755 μs
Wall time: 855 μs

0    foo
1    bar
2    baz
3    qux
4    foo
5    bar
6    baz
7    qux
dtype: category
Categories (4, str): ['bar', 'baz', 'foo', 'qux']

In [168]:
s = pd.Series(['a','b','c','d']*2)
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: str

In [169]:
cat_s =s.astype('category')

In [170]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [171]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
actual_categories = ['a','b','c','d','e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2
# 通过.cat.set_categories更改数据实际类别

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, str): ['a', 'b', 'c', 'd', 'e']

In [175]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [176]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [ ]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]
# 从cat_s中筛出类别为a,b的行，此时出现多余分类
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, str): ['a', 'b', 'c', 'd']

In [ ]:
cat_s3.cat.remove_unused_categories()
# 通过该方法删除未观察到的分类

0    a
1    b
4    a
5    b
dtype: category
Categories (2, str): ['a', 'b']